--- Makefile
+++ Makefile
@@ -16,6 +16,9 @@
 OBJ += log.o misc_tools.o prompt.o settings.o toxic.o toxic_strings.o windows.o message_queue.o
 OBJ += group_commands.o term_mplex.o avatars.o name_lookup.o
 
+# Include all needed checks
+-include $(CFG_DIR)/checks/check_features.mk
+
 # Check on wich system we are running
 UNAME_S = $(shell uname -s)
 ifeq ($(UNAME_S), Linux)
@@ -46,9 +49,6 @@
     -include $(CFG_DIR)/platforms/arm.mk
 endif
 
-# Include all needed checks
--include $(CFG_DIR)/checks/check_features.mk
-
 # Fix path for object files
 OBJ := $(addprefix $(BUILD_DIR)/, $(OBJ))
 
@@ -57,19 +57,19 @@
 
 $(BUILD_DIR)/toxic: $(OBJ)
 	@echo "  LD    $(@:$(BUILD_DIR)/%=%)"
-	@$(CC) $(CFLAGS) -o $(BUILD_DIR)/toxic $(OBJ) $(LDFLAGS)
+	$(CC) $(CFLAGS) -o $(BUILD_DIR)/toxic $(OBJ) $(LDFLAGS)
 
 $(BUILD_DIR)/osx_video.o: $(SRC_DIR)/$(OSX_VIDEO)
 	@echo "  CC    $(@:$(BUILD_DIR)/)osx_video.o"
-	@$(CC) $(CFLAGS) -o $(BUILD_DIR)/osx_video.o -c $(SRC_DIR)/$(OSX_VIDEO)
+	$(CC) $(CFLAGS) -o $(BUILD_DIR)/osx_video.o -c $(SRC_DIR)/$(OSX_VIDEO)
 
 $(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
 	@if [ ! -e $(BUILD_DIR) ]; then \
 		mkdir -p $(BUILD_DIR) ;\
 	fi
 	@echo "  CC    $(@:$(BUILD_DIR)/%=%)"
-	@$(CC) $(CFLAGS) -o $(BUILD_DIR)/$*.o -c $(SRC_DIR)/$*.c
-	@$(CC) -MM $(CFLAGS) $(SRC_DIR)/$*.c > $(BUILD_DIR)/$*.d
+	$(CC) $(CFLAGS) -o $(BUILD_DIR)/$*.o -c $(SRC_DIR)/$*.c
+	$(CC) -MM $(CFLAGS) $(SRC_DIR)/$*.c > $(BUILD_DIR)/$*.d
 
 clean:
 	rm -f $(BUILD_DIR)/*.d $(BUILD_DIR)/*.o $(BUILD_DIR)/toxic
