post_install() {
    systemd-sysusers tox-bootstrapd.conf
    test -d var/lib/tox-bootstrapd || install -d -m 0700 -o tox-bootstrapd -g tox-bootstrapd var/lib/tox-bootstrapd
    systemd-tmpfiles --create tox-bootstrapd.conf
}

post_upgrade() {
    systemctl status tox-bootstrapd && systemctl restart tox-bootstrapd
}

pre_remove() {
    systemctl status tox-bootstrapd && systemctl stop tox-bootstrapd
}
